// +build author

package smuggol

import (
	. "./terst"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

var base = ""

func testMain(dst, src string, extra map[string]string) error {
	dst = filepath.FromSlash(dst)
	dst = filepath.Join(base, dst)
	err := os.MkdirAll(dst, 0777)
	if err != nil {
		return err
	}
	return main(dst, src, extra)
}

func exists(path string, match ...string) {
	pth := filepath.FromSlash(path)
	pth = filepath.Join(base, pth)
	file, err := ioutil.ReadFile(pth)
	Is(err, nil)
	for _, match := range match {
		Is(regexp.MustCompile(match).Match(file), true, fmt.Sprintf("%s: %s", path, match))
	}
}

func Test(t *testing.T) {
	Terst(t)

	var err error

	base, err = ioutil.TempDir("", "smuggol.")
	Is(err, nil)
	if err != nil {
		FailNow()
	}
	defer os.RemoveAll(base)

	extra := map[string]string{
		"terst.go": `
            package {{ .HostPackage }}

            import (
                "{{ .ImportPath }}"
            )
        `,
	}

	mainName = "asdf-import"
	mainPkg = "github.com/robertkrimen/terst"
	flag_quiet = false
	flag_update = true

	// This will fail because we're asking smuggol to deposit a generated file without having
	// a proper Go package exist at the destination
	err = testMain("test/asdf", mainPkg, extra)
	IsNot(err, nil)

	// This, however, will succeed.
	err = testMain("test/asdf", mainPkg, nil)
	Is(err, nil)
	exists("test/asdf/terst/terst.go",
		"This file was AUTOMATICALLY GENERATED by asdf-import \\(smuggol\\) from github.com/robertkrimen/terst",
		"(?m)^package terst",
		"(?m)^func Is\\(",
	)

	ioutil.WriteFile(filepath.Join(base, filepath.FromSlash("test/asdf/asdf.go")), []byte("package asdf\n"), 0666)
	err = testMain("test/asdf", mainPkg, extra)
	Is(err, nil)
	exists("test/asdf/terst.go",
		"This file was AUTOMATICALLY GENERATED by asdf-import \\(smuggol\\) for github.com/robertkrimen/terst",
		"(?m)^package asdf",
	)

	_gofmt = false
	err = testMain("test/asdf", mainPkg, extra)
	Is(err, nil)
	exists("test/asdf/terst.go",
		"This file was AUTOMATICALLY GENERATED by asdf-import \\(smuggol\\) for github.com/robertkrimen/terst",
		"(?m)^\\s+package asdf",
	)

	// TODO
	// "test/xyzzy"
	// "test/xyzzy/xyzzy.go": package xyzzy\n...

}
